name: New Language Ecommerce CI

on:
  # push:
  # branches: [ main ]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test --if-present
      - name: Install and build client
        working-directory: ./client
        run: npm ci
        run: npm run build
      # - run: npm run build-client
